### ISSUE TITLE
Build fails with Xcode 26.4

### ISSUE THREAD

**Issue by shuguenot** [openid/AppAuth-iOS#947]
## Description

AppAuth 2.0.0 fails to compile with Xcode 26.4.0 (Apple clang 21) due to GNU case ranges being reclassified as a C2y extension.

## Error

```
OIDTokenUtilities.m:64:12: error: case ranges are a C2y extension [-Werror,-Wc2y-extensions]
    case 1 ... 8:
            ^
```

The project enables `-Werror`, which promotes this new warning into a fatal error.

## Environment

- Xcode 26.4.0
- AppAuth 2.0.0

**Comment by flabrie** [comment]
Same thing here. I also get failure with **Xcode 26.4.1** as well.

**Comment by w-goog** [comment]
This should be fixed in the 3.0.0 release :)
